services:
  http:
    container_name: filament-demo-http
    restart: always
    image: nginx:1.24
    volumes:
      - ./:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.http.routers.filament-demo-http.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.filament-demo-http.entrypoints=websecure
      - traefik.http.routers.filament-demo-http.tls=true
      - traefik.http.routers.filament-demo-http.tls.certresolver=letsencrypt
    networks:
      - ffh-network
      - internal
  php:
    container_name: filament-demo-php
    restart: always
    build:
      context: ./docker/php/
      dockerfile: prod.Dockerfile
    volumes:
      - ./:/app/
    networks:
      - internal
  node:
    container_name: filament-demo-node
    image: node:18
    volumes:
      - ./:/app/
    working_dir: /app/
    command: 'npm run build'
    networks:
      - internal
networks:
  ffh-network:
    name: ffh-network
  ffh-bdd:
    name: ffh-bdd
  internal:
    external: false
